EWB-465_Add-Names-to-evolve-grpc
zepben/evolve-grpc pull request #17
Opened 2021-02-03 01:00 UTC by var-ram

2021-02-03 01:00 UTC, var-ram commented
Task linked: [EWB-465 Add Names to evolve-grpc](https://app.clickup.com/t/6929263/EWB-465)

2021-02-04 01:27 UTC, gcarwardine requested changes

2021-02-04 01:27 UTC, gcarwardine commented on proto/zepben/protobuf/cim/iec61970/base/core/Name.proto
> +  NameType type = 2;
I don't think this should be a NameType. It means every identified object that comes back with a name will be sent with a full NameType. We don't want this. This hsould probably just be the name type name.

2021-02-04 02:24 UTC, gcarwardine approved these changes

2021-02-04 02:25 UTC, gcarwardine commented
I'm now happy with this in principle @var-ram. However let's not merge this until you flesh out some of the implementation in the SDK. You can obviously install locally to develop against. Are you happy with that?

2021-02-04 03:02 UTC, var-ram commented
> I'm now happy with this in principle @var-ram. However let's not merge this until you flesh out some of the implementation in the SDK. You can obviously install locally to develop against. Are you happy with that?

Oh yes. That's what I had in mind. 👍

2021-02-19 01:34 UTC, merged