Ewb 518 add load break switch
zepben/evolve-grpc pull request #18
Opened 2021-02-15 06:11 UTC by roberto-marquez

2021-02-15 22:21 UTC, kgreav requested changes

2021-02-15 22:21 UTC, kgreav commented on proto/zepben/protobuf/cim/iec61970/base/wires/LoadBreakSwitch.proto
> +  wires.ProtectedSwitch ps = 1;
the `wires.` here shouldn't be necessary

2021-02-15 22:59 UTC, kgreav approved these changes

2021-02-18 23:22 UTC, gcarwardine approved these changes

2021-02-18 23:22 UTC, merged